# NOR Gate Perceptron

$$
Y = \overline{A + B}
$$

In [1]:
import jax.numpy as np
import jax

## Input and Output

In [2]:
X = np.array(
    [
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1],
    ]
)

Y = np.array([[1], [0], [0], [0]])  

## Activation Function

* Sigmoid Function
* derivative of Sigmoid

In [3]:
@jax.jit
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
@jax.jit
def dervativeSigmoid(x):
    return x * (1 - x)

## Random Weights and Bias

In [5]:
key = jax.random.PRNGKey(31)

In [6]:
keyWeights, keyBias = jax.random.split(key)
keyWeights, keyBias

(Array([3383336270,  606859335], dtype=uint32),
 Array([3495797044, 3024489638], dtype=uint32))

In [7]:
weights = jax.random.normal(keyWeights, (2, 1))
weights

Array([[1.9952931 ],
       [0.32006642]], dtype=float32)

In [8]:
bias = jax.random.normal(keyBias, (1,))
bias

Array([0.05312927], dtype=float32)

In [9]:
lr = 10

## Training

In [10]:
for epoch in np.arange(10000):
    
    # Forward Propagation
    predict = sigmoid(np.dot(X, weights)+bias)

    # Error Calculation
    error = Y - predict

    # Backpropagation
    derivativePredict = dervativeSigmoid(predict)*error

    weights += np.dot(X.T, derivativePredict) * lr
    bias += np.sum(derivativePredict) * lr

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Error: {np.mean(np.abs(error))*100}%")

Epoch 0, Error: 71.97830963134766%
Epoch 1000, Error: 0.9195150136947632%
Epoch 2000, Error: 0.6450508832931519%
Epoch 3000, Error: 0.5248470306396484%
Epoch 4000, Error: 0.45359256863594055%
Epoch 5000, Error: 0.4051348567008972%
Epoch 6000, Error: 0.36945030093193054%
Epoch 7000, Error: 0.3417696952819824%
Epoch 8000, Error: 0.3194907307624817%
Epoch 9000, Error: 0.301056832075119%


## Final Weights and Bias

In [12]:
weights, bias

(Array([[-11.029777],
        [-11.029777]], dtype=float32),
 Array([5.2843423], dtype=float32))

## Prediction

In [13]:
sigmoid(np.dot(X, weights)+bias)

Array([[9.9495524e-01],
       [3.1871551e-03],
       [3.1871551e-03],
       [5.1834419e-08]], dtype=float32)

In [14]:
sigmoid(np.dot(X, weights)+bias).round()

Array([[1.],
       [0.],
       [0.],
       [0.]], dtype=float32)